# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    assignees:
      - "slavcodev"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "slavcodev"
